name: SkyMaster
version: '${project.version}'
main: com.itedya.skymaster.SkyMaster
api-version: 1.18
authors: [ itedya ]
website: itedya.com
depend:
  - WorldGuard
  - FastAsyncWorldEdit
permissions:
  kasix-mc.islands.create-schematic:
    description: Daje dostęp do tworzenia schematów.